version: '3'
services:
  app:
    image: ${DOCKER_USERNAME}/edc-steal-share:latest
    container_name: edc-steal-share
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
