version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/edc-steal-share:latest
    container_name: edc-steal-share
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
