version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/edc-steal-share:latest
    container_name: edc-steal-share
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    networks:
      - app-network
    links:
      - redis
      - postgres

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: bridge
