version: '3'
services:
  app:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Specify the Dockerfile name if it's not the default
    image: ${DOCKER_USERNAME}/edc-steal-share:latest
    container_name: edc-steal-share
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres  # Add PostgreSQL dependency
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: ${DATABASE_URL} # Update with your DB credentials
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --bind 0.0.0.0
    ports:
      - "6379:6379"
    restart: always

  postgres:  # Add PostgreSQL service
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres  # Set your DB user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Set your DB password
      POSTGRES_DB: ${POSTGRES_DB}  # Set your DB name
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    restart: always
